[project]
name = "codex-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "youtube-transcript-api>=0.6.1"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]
